name: jwt_hero
description: "JWT Hero is a Flutter package that helps you to manage JWT tokens in your Flutter app."
version: 0.3.2
homepage: https://github.com/Synapse-Squad/jwt-hero
issue_tracker: https://github.com/Synapse-Squad/jwt-hero/issues
topics: [jwt, auth, security]
platforms:
    android:
    ios:

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  dart_jsonwebtoken: ^2.17.0
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  kanza_lints: ^1.0.4

screenshots:
  - description: "Logo"
    path: screenshots/screenshot.png
